import math

# game settings

RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

MAZE_N_ROWS = 9
MAZE_N_COLS = 16

FPS = 60

PLAYER_POS = 1.5, 5 # in mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

MAP_VIEW_XO = 50
MAP_VIEW_YO = 50
MAP_VIEW_TILE_SCALE = 10
MAP_VIEW_XS = MAZE_N_COLS * MAP_VIEW_TILE_SCALE
MAP_VIEW_YS = MAZE_N_ROWS  * MAP_VIEW_TILE_SCALE
MAP_VIEW_PLAYER_RAY_LENGTH = 1 * MAP_VIEW_TILE_SCALE

def Main():
    pass

if __name__=="__main__":
    Main()